language: php

env:
  global:
    - disable-xdebug=true

git:
  depth: 2

matrix:
  include:
    - php: hhvm
      env: disable-xdebug=false
    - php: nightly
      env: disable-xdebug=false
    - php: 7.1
      env: disable-xdebug=false
    - php: 7.0
      env: disable-xdebug=true
    - php: 5.6
      env: disable-xdebug=true
  fast_finish: true

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.php-cs-fixer

notifications:
  email: false

before_script:
  - if [[ $disable-xdebug = true ]]; then
      phpenv config-rm xdebug.ini;
    fi
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction
  - travis_retry composer dump-autoload --optimize

script:
  # Use custom script to avoid the risk of terminating the build process
  - ./bin/travis/fail-non-feature-topic-branch-pull-request
  # Verify coding standard compliance only once
  - if [[ $TRAVIS_PHP_VERSION = 7.1 ]]; then
      composer ctl:cs-lint;
    fi
  - if [[ $(( $TRAVIS_BUILD_NUMBER % 25 )) = 0 ]]; then
      composer ctl:test-all;
    else
      composer ctl:test;
    fi
