language: php

git:
  depth: 2

matrix:
  include:
    - php: hhvm-3.9
      sudo: required
      dist: trusty
      group: edge
    - php: nightly
    - php: 7.1
      env: LINT=true VALIDATE_GITATTRIBUTES=true
    - php: 7.0
    - php: 5.6
  fast_finish: true
  allow_failures:
    - php: nightly

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.php-cs-fixer

notifications:
  email: false

before_script:
  - phpenv config-rm xdebug.ini || true
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction
  - travis_retry composer dump-autoload --optimize

script:
  # Use custom script to avoid the risk of terminating the build process
  - ./bin/travis/fail-non-feature-topic-branch-pull-request
  # Verify coding standard compliance only once
  - if [[ $LINT = true ]]; then
      composer ctl:cs-lint;
    fi
  - if [[ $VALIDATE_GITATTRIBUTES = true ]]; then
      composer ctl:gitattributes-validation;
    fi
  - if [[ $(( $TRAVIS_BUILD_NUMBER % 25 )) = 0 ]]; then
      composer ctl:test-all;
    else
      composer ctl:test;
    fi
